from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session, joinedload

from engenharia_zero import models, schemas, database

app = FastAPI()


@app.get("/")
def read_root():
    return {"message": "Engenharia Zero API ativa e conectada ao banco"}


@app.get("/users/", response_model=list[schemas.User])
def read_users(skip: int = 0, limit: int = 10, db: Session = Depends(database.get_db)):
    # The .offset(skip) option skips records (page 2, 3...)
    # The .limit(limit) option ensures that you don't crash the server with too much data
    users = db.query(models.UserTable).offset(skip).limit(limit).all()
    return users


@app.get("/products/", response_model=list[schemas.Product])
def read_products(
    skip: int = 0, limit: int = 10, db: Session = Depends(database.get_db)
):
    # The .offset(skip) option skips records (page 2, 3...)
    # The .limit(limit) option ensures that you don't crash the server with too much data
    products = db.query(models.ProductTable).offset(skip).limit(limit).all()
    return products


@app.get("/invoices/", response_model=list[schemas.Invoice])
def read_invoices(
    skip: int = 0, limit: int = 10, db: Session = Depends(database.get_db)
):
    # The .offset(skip) option skips records (page 2, 3...)
    # The .limit(limit) option ensures that you don't crash the server with too much data
    invoices = (
        db.query(models.InvoiceTable)
        .options(
            joinedload(models.InvoiceTable.items).joinedload(  # Load the items
                models.InvoiceItemTable.product
            )  # Load the product for each item
        )
        .offset(skip)
        .limit(limit)
        .all()
    )
    return invoices


@app.get("/invoices/{invoice_id}", response_model=schemas.Invoice)
def read_invoice(invoice_id: int, db: Session = Depends(database.get_db)):
    # .filter(models.InvoiceTable.id == invoice_id) is our WHERE clause where id = ?
    # .first() returns the object or None if nothing is found
    invoice = (
        db.query(models.InvoiceTable)
        .filter(models.InvoiceTable.id == invoice_id)
        .first()
    )

    if invoice is None:
        raise HTTPException(status_code=404, detail="Fatura não encontrada")

    return invoice


@app.post("/users/", status_code=201)
def create_user(user: schemas.UserCreate, db: Session = Depends(database.get_db)):
    # Business Rule Verification: unique e-mail
    db_user = (
        db.query(models.UserTable).filter(models.UserTable.email == user.email).first()
    )
    if db_user:
        raise HTTPException(status_code=400, detail="E-mail já cadastrado no sistema")

    # Conversion: Pydantic -> SQLAchemy
    new_user = models.UserTable(name=user.name, age=user.age, email=user.email)

    db.add(new_user)
    db.commit()
    db.refresh(new_user)  # Update the object with the ID generated by the data base
    return new_user


@app.post("/products/", response_model=schemas.Product)
def create_product(
    product: schemas.ProductCreate, db: Session = Depends(database.get_db)
):
    new_product = models.ProductTable(**product.model_dump())
    db.add(new_product)
    db.commit()
    db.refresh(new_product)
    return new_product


@app.post("/invoices/", response_model=schemas.Invoice)
def create_invoice(
    invoice_data: schemas.InvoiceCreate, db: Session = Depends(database.get_db)
):
    try:
        # 1. Validates if the user exists before start
        user_exists = (
            db.query(models.UserTable)
            .filter(models.UserTable.id == invoice_data.user_id)
            .first()
        )
        if not user_exists:
            raise HTTPException(status_code=404, detail="Usuário não encontrado")

        # 2. Create the Invoice (Header)
        new_invoice = models.InvoiceTable(user_id=invoice_data.user_id)
        db.add(new_invoice)
        db.flush()  # Ensure we have the new_invoice.id

        # 3. Create the Items (Body)
        for item in invoice_data.items:
            # Validates if the product exists
            product_exists = (
                db.query(models.ProductTable)
                .filter(models.ProductTable.id == item.product_id)
                .first()
            )
            if not product_exists:
                db.rollback()  # Cancel EVERYTHING that was done above
                raise HTTPException(
                    status_code=400, detail=f"Produto {item.product_id} não existe"
                )

            db_item = models.InvoiceItemTable(
                invoice_id=new_invoice.id,
                product_id=item.product_id,
                quantity=item.quantity,
                unit_price=product_exists.price,  # Here we save the current price!
            )
            db.add(db_item)

        # 4. Final Commit (Only gets here if everything went well)
        db.commit()
        db.refresh(new_invoice)
        return new_invoice

    except Exception as e:
        db.rollback()  # Extra security for any unexpected errors
        if isinstance(e, HTTPException):
            raise e
        raise HTTPException(status_code=500, detail="Erro interno ao processar fatura")
