from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session

from engenharia_zero.models import User
from engenharia_zero.database import UserTable, SessionLocal

app = FastAPI()


# 1. The "magic" of Dependency Injection
# This function opens the data base, provides the connection to the function, and then closes it
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


@app.get("/")
def read_root():
    return {"message": "Engenharia Zero API ativa e conectada ao banco"}


@app.get("/users/", response_model=list[User])
def read_users(skip: int = 0, limit: int = 10, db: Session = Depends(get_db)):
    # The .offset(skip) option skips records (page 2, 3...)
    # The .limit(limit) option ensures that you don't crash the server with too much data.
    users = db.query(UserTable).offset(skip).limit(limit).all()
    return users


@app.post("/users/", status_code=201)
def create_user(user: User, db: Session = Depends(get_db)):
    # Business Rule Verification: unique e-mail
    db_user = db.query(UserTable).filter(UserTable.email == user.email).first()
    if db_user:
        raise HTTPException(status_code=400, detail="E-mail já cadastrado no sistema")

    # Conversion: Pydantic -> SQLAchemy
    new_user = UserTable(name=user.name, age=user.age, email=user.email)

    db.add(new_user)
    db.commit()
    db.refresh(new_user)  # Update the object with the ID generated by the data base
    return new_user
