from collections.abc import Sequence
from typing import Any
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core import UserNotFoundError
from app.db import models
from app.schemas import UserCreate


class UserRepository:
    def __init__(self, db: Session) -> None:
        self.db = db

    def get_by_id(self, user_id: int) -> models.UserTable | None:
        return (
            self.db.query(models.UserTable)
            .filter(models.UserTable.user_id == user_id)
            .first()
        )

    def get_by_uuid(self, user_uuid_id: UUID) -> models.UserTable | None:
        return (
            self.db.query(models.UserTable)
            .filter(models.UserTable.user_uuid_id == user_uuid_id)
            .first()
        )

    def get_by_email(self, email: str) -> models.UserTable | None:
        return (
            self.db.query(models.UserTable)
            .filter(models.UserTable.email == email)
            .first()
        )

    def get_all(self, skip: int = 0, limit: int = 10) -> Sequence[models.UserTable]:
        # scalars().all() retorna uma Sequence, que é mais preciso que list para leitura
        query = select(models.UserTable).offset(skip).limit(limit)
        return self.db.scalars(query).all()

    def get_hashed_password(self, user_id: int) -> str | None:
        db_user = self.get_by_id(user_id)
        if not db_user:
            raise UserNotFoundError(f"Usuário com ID {user_id} não encontrado")
        return db_user.hashed_password if db_user else None

    def create(self, user: UserCreate) -> models.UserTable:
        # Conversion: Pydantic -> SQLAlchemy
        new_user = models.UserTable(
            name=user.name,
            email=user.email,
            birth_date=user.birth_date,
            telephone=user.telephone,
            hashed_password=user.password,
            # is_admin will be False by default
        )

        self.db.add(new_user)
        self.db.commit()
        self.db.refresh(
            new_user
        )  # Update the object with the ID generated by the data base
        return new_user

    def update(
        self, user_id: int, update_data: dict[str, Any]
    ) -> models.UserTable | None:
        db_user = self.get_by_id(user_id)
        if db_user:
            for key, value in update_data.items():
                setattr(db_user, key, value)
            self.db.commit()
            self.db.refresh(db_user)
        return db_user

    def update_password(self, user_id: int, new_hashed_password: str) -> None:
        db_user = self.get_by_id(user_id)
        if db_user:
            db_user.hashed_password = new_hashed_password
            self.db.commit()
        return None
