"""add unit_price and constraints

Revision ID: 52e8470a5e17
Revises: e5afed154d70
Create Date: 2026-04-20 19:20:35.647560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e8470a5e17'
down_revision: Union[str, Sequence[str], None] = 'e5afed154d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('unit_price', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###

    # ### Human-written commands - SQL to copy the current price of products to existing itens ###
    op.execute(
        "UPDATE invoice_items SET unit_price = (SELECT price FROM products WHERE products.id = invoice_items.product_id)"
    )
    # ### end Human-written commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'unit_price')
    # ### end Alembic commands ###
